spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: postgres
    password: kvasik225
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false
    change-log: classpath:db.changelog/db.changelog-master.xml

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 30000
          user-service:
            connect-timeout: 10000
            read-timeout: 60000

server:
  port: 8080
