# Test properties
spring.datasource.url=jdbc:tc:postgresql:15-alpine:///testdb
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# WireMock configuration
user.service.base-url=http://localhost:8089

# Test logging
logging.level.com.innowise.rudkovskii=DEBUG